CREATE TABLE IF NOT EXISTS organization
(
    id INTEGER PRIMARY KEY,
    name CHARACTER VARYING(60) NOT NULL
);
CREATE SEQUENCE organization_id_seq START WITH 0 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS faculty
(
    id INTEGER PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organization (id) ON DELETE CASCADE ON UPDATE CASCADE,
    name CHARACTER VARYING(60) NOT NULL,
    CONSTRAINT student_indicator_combination UNIQUE (organization_id, name)
);
CREATE IF NOT EXISTS SEQUENCE faculty_id_seq START WITH 0 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS program
(
    id INTEGER PRIMARY KEY,
    faculty_id INTEGER NOT NULL REFERENCES faculty (id) ON DELETE CASCADE ON UPDATE CASCADE,
    code CHARACTER VARYING(12) NOT NULL,
    name CHARACTER VARYING(60) NOT NULL
);
CREATE IF NOT EXISTS SEQUENCE program_id_seq START WITH 0 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS profile
(
    id INTEGER PRIMARY KEY,
    program_id INTEGER NOT NULL REFERENCES program (id) ON DELETE CASCADE ON UPDATE CASCADE,
    name CHARACTER VARYING(60) NOT NULL
);
CREATE IF NOT EXISTS SEQUENCE profile_id_seq START WITH 0 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS teacher
(
    id INTEGER PRIMARY KEY,
);
CREATE IF NOT EXISTS SEQUENCE teacher_id_seq START WITH 0 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS discipline
(
    id INTEGER PRIMARY KEY,
    profile_id INTEGER NOT NULL REFERENCES profile (id) ON DELETE CASCADE ON UPDATE CASCADE,
    teacher_id INTEGER NOT NULL REFERENCES teacher (id) ON DELETE CASCADE ON UPDATE CASCADE,
    semester INTEGER NOT NULL,
    name CHARACTER VARYING(60) NOT NULL,
    CONSTRAINT prfile_techer_semester_combination UNIQUE (profile_id, teacher_id, semester)
);
CREATE IF NOT EXISTS SEQUENCE discipline_id_seq START WITH 0 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS indicator_group
(
    id INTEGER PRIMARY KEY,
    name CHARACTER VARYING(60) NOT NULL
);
CREATE IF NOT EXISTS SEQUENCE indicator_group_id_seq START WITH 0 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS indicator
(
    id INTEGER PRIMARY KEY,
    group_id INTEGER NOT NULL REFERENCES indicator_group (id) ON DELETE CASCADE ON UPDATE CASCADE,
    discipline_id INTEGER NOT NULL REFERENCES discipline (id) ON DELETE CASCADE ON UPDATE CASCADE,
    name CHARACTER VARYING(60) NOT NULL,
    max_value INTEGER NOT NULL
);
CREATE IF NOT EXISTS SEQUENCE indicator_id_seq START WITH 0 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS student
(
    id INTEGER PRIMARY KEY
);
CREATE IF NOT EXISTS SEQUENCE student_id_seq START WITH 0 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS result
(
    id INTEGER PRIMARY KEY,
    indicator_id INTEGER NOT NULL REFERENCES indicator (id) ON DELETE CASCADE ON UPDATE CASCADE,
    student_id INTEGER NOT NULL REFERENCES student (id) ON DELETE CASCADE ON UPDATE CASCADE,
    value DOUBLE PRECISION NOT NULL,
    is_prediction BOOLEAN NOT NULL,
    CONSTRAINT student_indicator_combination UNIQUE (indicator_id, student_id)
);
CREATE IF NOT EXISTS SEQUENCE result_id_seq START WITH 0 INCREMENT BY 1;